# Perfect Podcast Proxy Configuration

[RSS_Import]
#When adding a new podcast feed, how many days back should we initially consider?
#This can be manually altered later in data/feeds.json, if you didn't notice this setting before
initial_podcast_lookback = 7

[transcribe]
# (Faster)Whisper model to use. Options: "tiny", "base", "small", "medium", "large"
# Append ".en" (e.g., "small.en") for faster, more accurate English-only transcription.
# Code will automatically use CUDA or Apple Silicon if available (and will tell you when you trigger a transcribe, which it's using)
# small.en is about realtime on a CPU - maybe 20x faster on GPU
# going up from small to large is roughly trebling the transcription time
model_to_use = "small.en"


[ollama]
#We're using Ollama to detect the adverts. i.e. These are separate models to transcribing configured above
ollama_url = "http://localhost:11434/api/chat"
#Mode to use for detecting adverts, based on whether it's GPU or not
gpu_model = "qwen3:14b"
cpu_model = "qwen2.5:7b"


[processing]
# Set to true to force CPU-only processing, even if a GPU is available.
# I'm just using this for testing. No good reason you should ever change this
force_cpu = false
# Set to true to insert a subtle 'pop' sound where an advert/segment was deleted
insert_edit_pop = true

[content_to_remove]
# Select which categories of content you wish to extract and remove from the podcast
sponsor_read = true
podcast_promotion = true
self_promotion = false
intro_outro = false
show_content = false
other = false

[export]
# Set to true to activate exporting of cleaned podcasts to a separate directory
export_activated = true
# The path where the web folder structure should be built. E.g. "C:/my_web_server/podcasts"
export_path = "W:/ppp"
# The base URL where this folder will be hosted. E.g. "http://192.168.1.100/ppp"
base_url = "https://bobpitch.com/ppp"
