# Perfect Podcast Proxy Configuration


[RSS_Import]
#When adding a new podcast feed, how many days back should we initially consider?
#This can be manually tweaked in data/feeds.json
initial_podcast_lookback = 7

[transcribe]
# (Faster)Whisper model to use. Options: "tiny", "base", "small", "medium", "large"
# Append ".en" (e.g., "small.en") for faster, more accurate English-only transcription.
# Code will automatically use CUDA or Apple Silicon if available (and will tell you when you trigger a transcribe, which it's using)
# small.en is about realtime on a CPU - maybe 20x faster on GPU
# going up from small to large is roughly trebling the transcription time
model_to_use = "small.en"


