# Perfect Podcast Proxy Configuration


[RSS_Import]
#When adding a new podcast feed, how many days back should we initially consider?
#This can be manually tweaked in data/feeds.json
initial_podcast_lookback = 7

[transcribe]
# Whisper model to use. Options: "tiny", "base", "small", "medium", "large"
# Append ".en" (e.g., "small.en") for faster, more accurate English-only transcription.
model_to_use = "small.en"


